name: agrijardin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.9
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
  - assets/images/logo_app.png
